#!/bin/bash

if [ -z "$DATA_DIR" ]
then
	DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
    export DATA_DIR=${DIR}/../../data
fi

#./dwt2d ${DATA_DIR}/dwt2d/192.bmp -d 192x192 -f -5 -l 3
./dwt2d.out rgb.bmp -d 1024x1024 -f -5 -l 3
