#!/bin/bash

if [ -z "$DATA_DIR" ]
then
	DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
    export DATA_DIR=${DIR}/../../data
fi

echo "__cudaRegisterVar is not yet supported by AvA"
./heartwall ${DATA_DIR}/heartwall/test.avi 100
